language: node_js
node_js:
  - '0.10'
before_script:
  - ./node_modules/bower/bin/bower install
after_success:
  - ./node_modules/grunt-cli/bin/grunt coveralls
cache:
  directories:
    - node_modules
env:
  global:
    - COVERALLS_SERVICE_NAME="travis-ci"
    - secure: "gRReaTKLPsQFrcNccJHYJztHCOmGiorT9oqRHA2YeH4m1jV7Kf8Ku8hjN+3zjMr4cFA8yUHAmf7rh+zUg5Ovo+DRx9L8PdsErgXGFGEmPBCTLALnnrXgZ20X7OrrTMu/sAXFh+r803SuldByci1TBDyH+S7bX76oRkj7sxjKSdc="
notifications:
  email: false
  webhooks:
    urls:
      secure: "BaZQ5HQaFoJQCDadWEg7NkGe7KTB+OuLOAjKE/LrUxhrrNjWFLcIIsI7fuDAaUEH3b+aEbx5WMbiIY4Tz+QL31Nl9Vqn47JuHFg+2aOyOiS11FTxvSIEV+iaAwAsikGRcYEn7356A2zkUU/6iYNNjaoyhjLXz/ub5ZaMd9NwuBk="
    on_start: true
