language: node_js
node_js:
  - '0.10'
before_script:
  - ./node_modules/bower/bin/bower install
after_success:
  - ./node_modules/grunt-cli/bin/grunt coveralls
cache:
  directories:
    - node_modules
env:
  global:
    - COVERALLS_SERVICE_NAME="travis-pro"
    - secure: "ke17kytjrriZjX0AVPxnsQm6uFR8AZ/ymb7b3wlUNoWc3E2nzyUj+07S9R81oMQGjyfXC6bb3t8+XcVBJAGDPbArCx59sBZKPMHM7hzUJTAb3eQB/ptgMDHneYLYNOqxSyvIHdC40wPoBdB3vlAgew4/31UHDe69RznQTicV5Iw="
notifications:
  email: false
  webhooks:
    urls:
      secure: "jyVHUjWUMJyWMzp3kCPm0D8OaBgaJGivVwNcvOR2l+6yxEMntQKNSiEBnY/A7e09y3shWTQCwzyJcZbnphno32nJiWhgy7V2CMbKzh1ruKgL34OW7+5Cqt6KrL5P4YRiW+2RDrp1E3Gjzv74ag/TtmWVZY+unJKWdDUV4pTHufg="
    on_start: true
