language: node_js
node_js:
  - '0.10'
before_script:
  - ./node_modules/bower/bin/bower install
after_success:
  - ./node_modules/grunt-cli/bin/grunt coveralls
cache:
  directories:
    - node_modules
env:
  global:
    - COVERALLS_SERVICE_NAME="travis-pro"
    - secure: "ke17kytjrriZjX0AVPxnsQm6uFR8AZ/ymb7b3wlUNoWc3E2nzyUj+07S9R81oMQGjyfXC6bb3t8+XcVBJAGDPbArCx59sBZKPMHM7hzUJTAb3eQB/ptgMDHneYLYNOqxSyvIHdC40wPoBdB3vlAgew4/31UHDe69RznQTicV5Iw="
notifications:
  email: false
  webhooks:
    urls:
      secure: "Z/bvJxxsKGb1jk2liw/SnllFQXotK8N/YU+5e4OrXzK9mWKUikm35C0EZEghUd2DUo2EgF3XtZse4h4W2QRySE3lNz5iKlk5eF8NMBdgZlmR0ZqP4x9xAgkr9u6Bk7TrDBLaOSbSjI2IaCmlcGcTVd4zkSYHTC7xPvRPqke+xpA="
    on_start: true
