language: node_js
node_js:
  - '0.10'
before_script:
  - ./node_modules/bower/bin/bower install
after_success:
  - ./node_modules/grunt-cli/bin/grunt coveralls
cache:
  directories:
    - node_modules
env:
  global:
    - COVERALLS_SERVICE_NAME="travis-ci"
    - secure: "gRReaTKLPsQFrcNccJHYJztHCOmGiorT9oqRHA2YeH4m1jV7Kf8Ku8hjN+3zjMr4cFA8yUHAmf7rh+zUg5Ovo+DRx9L8PdsErgXGFGEmPBCTLALnnrXgZ20X7OrrTMu/sAXFh+r803SuldByci1TBDyH+S7bX76oRkj7sxjKSdc="
notifications:
  email: false
  slack:
    secure: "DK9Jeix5GCmAkBfwdWa9f97dft4iIOqvxMN+XBbd0MWwKQV86VQq7hhJcXrGb3G1GhsaA5XBVuUxht4pStcsIadDkCfynDATd00r9Chlu9c4aLc2eQ5g5P3he+wa4iYHG8pLCtqq2S3YBxYc5Xja3rMmhOCSEwwu2gDSSyTyXFg="
